# Generated by Django 5.0.1 on 2024-01-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
